"""empty message

Revision ID: e90d35744312
Revises: 77cdd7c5605e
Create Date: 2020-06-08 15:14:14.845178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90d35744312'
down_revision = '77cdd7c5605e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('roles_users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'confirmed_At')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_At', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'confirmed_at')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_column('roles_users', 'role_id')
    op.drop_table('thread')
    # ### end Alembic commands ###
